from abc import ABC, abstractmethod
from datetime import date
from src.domain.entities import Repost, Sources, User
from src.domain.entities.task import OnlineTask, OfflineTask, AcceptedOfflineTask, TaskStatus, \
    TaskType
from src.domain.entities.user import UserRole


class IUserService(ABC):
    @abstractmethod
    async def create_user(self, user_id: int, username: str | None, surname: str, name: str, is_member: bool, patronymic: str | None, birth_date: date, phone_number: str, region: str, email: str, gender: str, city: str, wish_to_join: bool, home_address: str | None, news_subscription: bool) -> User: ...
    @abstractmethod
    async def is_user_exists(self, user_id: int, inviter_source: Sources | None = None) -> bool: ...
    @abstractmethod
    async def validate_phone(self, phone_number: str) -> str: ...
    @abstractmethod
    async def validate_email(self, email: str) -> str: ...
    @abstractmethod
    async def validate_fio_part(self, part: str, part_name: str) -> str: ...
    @abstractmethod
    async def get_similar_regions(self, region: str) -> list[str]: ...
    @abstractmethod
    async def get_region_address(self, region: str) -> str: ...
    @abstractmethod
    async def get_user_region(self, user_id: int) -> str: ...
    @abstractmethod
    async def get_all_users(self) -> list[User]: ...
    @abstractmethod
    async def update_news_subscription(self, user_id: int, news_subscription: bool) -> User: ...
    @abstractmethod
    async def get_region_by_prefix(self, region_prefix: str) -> str: ...
    @abstractmethod
    async def get_user_role(self, user_id: int, user_source: Sources) -> UserRole: ...


class IBalanceService(ABC):
    @abstractmethod
    async def get_balance(self, user_id: int, user_source: Sources) -> int: ...
    @abstractmethod
    async def add_balance(self, user_id: int, user_source: Sources, amount: int, description: str) -> None: ...


class IOnlineTaskService(ABC):
    @abstractmethod
    async def search_tasks(self, user_id: int, user_source: Sources, page: int = 1) -> tuple[list[OnlineTask], int]: ...
    @abstractmethod
    async def check_task(self, user_id: int, user_source: Sources, task_id: int) -> None: ...
    @abstractmethod
    async def get_task(self, task_id: int) -> OnlineTask | None: ...
    @abstractmethod
    async def create_task(self, date: date, duration: int, type: TaskType, reward: int, post_id: int, group_id: int) -> OnlineTask: ...


class IOfflineTaskService(ABC):
    @abstractmethod
    async def search_tasks(self, user_id: int, user_source: Sources, page: int = 1) -> tuple[list[OfflineTask], int]: ...
    @abstractmethod
    async def check_task(self, user_id: int, user_source: Sources, task_id: int, new_status: TaskStatus) -> None: ...
    @abstractmethod
    async def get_task(self, task_id: int) -> OfflineTask | None: ...
    @abstractmethod
    async def get_user_tasks(self, user_id: int, user_source: Sources, page: int = 1) -> tuple[list[AcceptedOfflineTask], int]: ...
    @abstractmethod
    async def cancel_task(self, user_id: int, user_source: Sources, task_id: int) -> None: ...
    @abstractmethod
    async def create_task_by_admin(self, region: str, date: date, reward: int, title: str, description: str, location: str, contacts: str) -> OfflineTask: ...
    @abstractmethod
    async def create_task_by_personal(self, user_id: int, user_source: Sources, date: date, reward: int, title: str, description: str, location: str, contacts: str) -> OfflineTask: ...


class IReferralService(ABC):
    @abstractmethod
    async def activate_referral(self, inviter_id: int, inviter_source: Sources, invitee_id: int,
                                invitee_source: Sources) -> None:
        ...

    @abstractmethod
    async def get_count_invitees(self, inviter: int, inviter_source: Sources) -> int:
        ...


class IReferralLinkService(ABC):
    @abstractmethod
    def generate_post(self, user_id: int) -> Repost:
        ...